### ISSUE TITLE
SSL Problem

### ISSUE THREAD

**Issue by eudomoniacc** [gyoisamurai/GyoiThon#12]
[*] Exception: HTTP Error 400: Bad Request
[*] Exception: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)>

Traceback (most recent call last):
  File "gyoithon.py", line 228, in <module>
    products = classifier.analyzer(ip_list[idx], int(port_list[idx]), ip_list[idx])
  File "./classifier4gyoithon/GyoiClassifier.py", line 95, in analyzer
    logfile_path = os.path.join(self.root_path, df_selected_summary.at[0, 'log'])
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/indexing.py", line 1869, in __getitem__
    return self.obj._get_value(*key, takeable=self._takeable)
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py", line 1985, in _get_value
    return engine.get_value(series._values, index)
  File "pandas/_libs/index.pyx", line 83, in pandas._libs.index.IndexEngine.get_value
  File "pandas/_libs/index.pyx", line 91, in pandas._libs.index.IndexEngine.get_value
  File "pandas/_libs/index.pyx", line 139, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 811, in pandas._libs.hashtable.Int64HashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 817, in pandas._libs.hashtable.Int64HashTable.get_item
KeyError: 0

By the way script is not compatible with python2.7 so i used python3.6. You need to adjust the script and ssl support according to that.

**Comment by gyoisamurai** [comment]
Hi, @eudomoniacc 
We changed from `urllib` to `urllib3` in `gyoithon.py` and `GyoiClassifier.py`.
Please, try again.
