### ISSUE TITLE
Another issue

### ISSUE THREAD

**Issue by eudomoniacc** [gyoisamurai/GyoiThon#13]
Thank you for update but i have this issue now :/

Invalid file: list index out of range
Traceback (most recent call last):
  File "gyoithon.py", line 202, in <module>
    if check_arg_value(ip_list[idx], port_list[idx], path_list[idx]) is False:
IndexError: list index out of range

**Comment by gyoisamurai** [comment]
Hi, @eudomoniacc 
Is content of `host.txt` following?
```
"target fqdn" "port number" "target path"
```

ex)
```
www.example.com 443 /contact.html
www.example.com 80 /about.html
```

**Comment by eudomoniacc** [comment]
yes i arranged like that, it seems to work but now i have this warning with urllib3 
Caused by ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')))
/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)

and also can i ask you to add ReverseListeningBindAdress and ReverseListeningBindPort implenmentation for ngrok usage since not every router is available for port forwarding.

**Comment by eudomoniacc** [comment]
and also now it seems like it is not stable with every http websites, tried on 2 websites and the result is like 
first one
[*] Invalid IP address
[*] Exception: 'utf-8' codec can't decode byte 0xed in position 264: invalid continuation byte
[*] Exception: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:833)
Traceback (most recent call last):
  File "gyoithon.py", line 232, in <module>
    products = classifier.analyzer(ip_list[idx], int(port_list[idx]), ip_list[idx])
  File "./classifier4gyoithon/GyoiClassifier.py", line 95, in analyzer
    logfile_path = os.path.join(self.root_path, df_selected_summary.at[0, 'log'])
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/indexing.py", line 1869, in __getitem__
    return self.obj._get_value(*key, takeable=self._takeable)
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py", line 1985, in _get_value
    return engine.get_value(series._values, index)
  File "pandas/_libs/index.pyx", line 83, in pandas._libs.index.IndexEngine.get_value
  File "pandas/_libs/index.pyx", line 91, in pandas._libs.index.IndexEngine.get_value
  File "pandas/_libs/index.pyx", line 139, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 811, in pandas._libs.hashtable.Int64HashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 817, in pandas._libs.hashtable.Int64HashTable.get_item

second one 
[*] Invalid IP address
[*] Exception: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:833)
