### ISSUE TITLE
why 

### ISSUE THREAD

**Issue by zhangchenyi88** [gyoisamurai/GyoiThon#19]
[] Invalid IP address
[] Exception: 'utf-8' codec can't decode byte 0xed in position 264: invalid continuation byte
[*] Exception: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:833)
Traceback (most recent call last):
File "gyoithon.py", line 232, in 
products = classifier.analyzer(ip_list[idx], int(port_list[idx]), ip_list[idx])
File "./classifier4gyoithon/GyoiClassifier.py", line 95, in analyzer
logfile_path = os.path.join(self.root_path, df_selected_summary.at[0, 'log'])
File "/usr/local/lib/python3.6/dist-packages/pandas/core/indexing.py", line 1869, in getitem
return self.obj._get_value(*key, takeable=self._takeable)
File "/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py", line 1985, in _get_value
return engine.get_value(series._values, index)
File "pandas/_libs/index.pyx", line 83, in pandas._libs.index.IndexEngine.get_value
File "pandas/_libs/index.pyx", line 91, in pandas._libs.index.IndexEngine.get_value
File "pandas/_libs/index.pyx", line 139, in pandas._libs.index.IndexEngine.get_loc
File "pandas/_libs/hashtable_class_helper.pxi", line 811, in pandas._libs.hashtable.Int64HashTable.get_item
File "pandas/_libs/hashtable_class_helper.pxi", line 817, in pandas._libs.hashtable.Int64HashTable.get_item

**Comment by gyoisamurai** [comment]
i updated the GyoiThon for adding web crawling function.
but, GyoiThon may include bugs.

so, i'll fix bug soon. please, just a moment.

**Comment by gyoisamurai** [comment]
i've fixed bugs.  
please, try again!!
