### ISSUE TITLE
Issue when trying to run GyoiThon

### ISSUE THREAD

**Issue by geniusKoder** [gyoisamurai/GyoiThon#31]
Here is the error. Thank you!

```
Traceback (most recent call last):
  File "gyoithon.py", line 212, in <module>
    cve_explorer = CveExplorerNVD(utility, opt_no_update_vulndb)
  File "/root/GyoiThon/modules/Gyoi_CveExplorerNVD.py", line 66, in __init__
    self.df_vuln_db = self.initialize_vuln_db()
  File "/root/GyoiThon/modules/Gyoi_CveExplorerNVD.py", line 282, in initialize_vuln_db
    df_vuln_db = pd.read_csv(self.nvd_path, sep=',', encoding='utf-8')
  File "/usr/local/lib/python3.7/dist-packages/pandas/io/parsers.py", line 702, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python3.7/dist-packages/pandas/io/parsers.py", line 429, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/usr/local/lib/python3.7/dist-packages/pandas/io/parsers.py", line 895, in __init__
    self._make_engine(self.engine)
  File "/usr/local/lib/python3.7/dist-packages/pandas/io/parsers.py", line 1122, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/usr/local/lib/python3.7/dist-packages/pandas/io/parsers.py", line 1853, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 387, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 705, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] File b'/root/GyoiThon/modules/vuln_db/vulns_nvd.csv' does not exist: b'/root/GyoiThon/modules/vuln_db/vulns_nvd.csv'
```

**Comment by geniusKoder** [comment]
I think the documentation can be modified to specify removing the proxy server argument in config.ini if no proxy server is used. After removing that, I'm getting new errors in trying to download the csv. Please help to look into it. Thank you very much!

```
[*] Get 2019 meta information from https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-2019.meta
[!] Set encoding: ASCII
[*] Get 2019 CVE list from https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-2019.json.zip
[!] type:<class 'AttributeError'>
[!] args:("'str' object has no attribute 'items'",)
[!] 'str' object has no attribute 'items'
[!] Access is failure : https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-2019.json.zip
[!] type:<class 'FileNotFoundError'>
[!] args:(2, 'No such file or directory')
[!] [Errno 2] No such file or directory: '/root/GyoiThon/modules/vuln_db/temp_2019.zip'
[!] Getting last modified date is failure.
[*] Load vulnerability database : /root/GyoiThon/modules/vuln_db/vulns_nvd.csv

```

**Comment by blshkv** [comment]
@geniusKoder I was porting the tool to Pentoo Linux yesterday and faced the same issue.
Please try this patch
