### ISSUE TITLE
Curl error on dockerfile

### ISSUE THREAD

**Issue by fargusplumdoodle** [gyoisamurai/GyoiThon#35]
Ive gotten this error when trying to build the docker file.
```fargus@Osiris:~/Projects/GyoiThon/docker$ docker build -t test_gyoithon .
Sending build context to Docker daemon  11.78kB
Step 1/11 : FROM kalilinux/kali-linux-docker
 ---> f26f3ae90aee
Step 2/11 : RUN apt-get update && apt-get install -y metasploit-framework tmux python3-pandas python3-docopt python3-msgpack python3-jinja2 && apt-get clean && rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> d050cacb411f
Step 3/11 : RUN curl -sSL https://github.com/gyoisamurai/GyoiThon/raw/master/docker/msf_setup/db.sql --output /tmp/db.sql
 ---> Using cache
 ---> e8f59287a411
Step 4/11 : RUN /etc/init.d/postgresql start && su postgres -c "psql -f /tmp/db.sql"
 ---> Using cache
 ---> ee9a61e99a09
Step 5/11 : RUN curl -sSL https://github.com/gyoisamurai/GyoiThon/raw/master/docker/msf_setup/database.yml --output /usr/share/metasploit-framework/config/database.yml
 ---> Using cache
 ---> 07377f25947f
Step 6/11 : RUN git clone https://github.com/gyoisamurai/GyoiThon /opt/gyiothon
 ---> Using cache
 ---> 6891ae93be7b
Step 7/11 : RUN curl -sSL https://github.com/gyoisamurai/GyoiThon/raw/master/docker/msf_setup/meterpreter.rc --output /tmp/meterpreter.rc
 ---> Using cache
 ---> 9eb5fa246460
Step 8/11 : RUN curl -sSL https://github.com/gyoisamurai/GyoiThon/raw/master/docker/gyoithon_setup/config.ini --output /opt/gyiothon/classifier4gyoithon/config.ini
 ---> Running in 158111af4eb5
curl: (23) Failed writing body (0 != 1131)
The command '/bin/sh -c curl -sSL https://github.com/gyoisamurai/GyoiThon/raw/master/docker/gyoithon_setup/config.ini --output /opt/gyiothon/classifier4gyoithon/config.ini' returned a non-zero code: 23
```

I looked up curls exit code 23, it means theres a write error. Something is wrong with writing to the file ``` /opt/gyiothon/classifier4gyoithon/config.ini```. Heres the link to the curl errors page:
https://curl.haxx.se/libcurl/c/libcurl-errors.html

**Comment by fargusplumdoodle** [comment]
```Sending build context to Docker daemon  13.82kB
Step 1/11 : FROM kalilinux/kali-linux-docker
 ---> f26f3ae90aee
Step 2/11 : RUN apt-get update && apt-get install -y metasploit-framework tmux python3-pandas python3-docopt python3-msgpack python3-jinja2 && apt-get clean && rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> d050cacb411f
Step 3/11 : RUN curl -sSL https://github.com/gyoisamurai/GyoiThon/raw/master/docker/msf_setup/db.sql --output /tmp/db.sql
 ---> Using cache
 ---> e8f59287a411
Step 4/11 : RUN /etc/init.d/postgresql start && su postgres -c "psql -f /tmp/db.sql"
 ---> Using cache
 ---> ee9a61e99a09
Step 5/11 : RUN curl -sSL https://github.com/gyoisamurai/GyoiThon/raw/master/docker/msf_setup/database.yml --output /usr/share/metasploit-framework/config/database.yml
 ---> Using cache
 ---> 07377f25947f
Step 6/11 : RUN git clone https://github.com/gyoisamurai/GyoiThon /opt/gyiothon
 ---> Using cache
 ---> 6891ae93be7b
Step 7/11 : RUN curl -sSL https://github.com/gyoisamurai/GyoiThon/raw/master/docker/msf_setup/meterpreter.rc --output /tmp/meterpreter.rc
 ---> Using cache
 ---> 9eb5fa246460
Step 8/11 : COPY ./gyoithon_setup/config.ini /opt/gyiothon/classifier4gyoithon/config.ini
 ---> cc67905fafa5
Step 9/11 : RUN find /opt/gyiothon -name "*.py" -type f | xargs sed -i -e '/OKGREEN + banner + ENDC/d'
 ---> Running in 68fd710e09c2
Removing intermediate container 68fd710e09c2
 ---> d8a77d3cc43d
Step 10/11 : WORKDIR "/opt/gyiothon/"
 ---> Running in 2683a99bbcdb
Removing intermediate container 2683a99bbcdb
 ---> c45867304088
Step 11/11 : CMD /etc/init.d/postgresql start; tmux new-session -d -s cool 'msfconsole -r /tmp/meterpreter.rc'; sleep 180; curl localhost:55553; python3 /opt/gyiothon/gyoithon.py
 ---> Running in b8ec6c2fa59a
Removing intermediate container b8ec6c2fa59a
 ---> 069cf43b8977
Successfully built 069cf43b8977
Successfully tagged test_gyoithon:latest
```

I was able to fix it by replaceing the curl with a COPY 
``` COPY ./gyoithon_setup/config.ini /opt/gyiothon/classifier4gyoithon/config.ini```

However only works because I have the repository on my local machine. The rest of the dockerfile seems as though its designed to be portable. Is there an easy fix for this?

**Comment by gyoisamurai** [comment]
Currently, Docker is old that out of maintain.  
So, please show bellow document for installation.  

https://github.com/gyoisamurai/GyoiThon/blob/master/README.md#Installation

**Comment by fargusplumdoodle** [comment]
It  would be very convient for for me to be able to run Gyoithon in docker. 
Ive been trying to hack together a dockerfile. But I keep encountering UnicodeEncoderErrors

The timezone fix  is because one of the requirements manually asked user for timezone. It just runs these commands to set the timezoene to America/Vancouver

timezonefix.sh
```bash
# set noninteractive installation                               
export DEBIAN_FRONTEND=noninteractive                           
#install tzdata package                                         
apt-get install -y tzdata                                       
# set your timezone                                             
ln -fs /usr/share/zoneinfo/America/Vancouver /etc/localtime     
dpkg-reconfigure --frontend noninteractive tzdata               
```
Dockerfile
```Dockerfile
FROM ubuntu
RUN apt-get update 

# preventing one of the installs from requesting user input
COPY ./timezonefix.sh /tmp/timezonefix.sh
RUN bash /tmp/timezonefix.sh

# installing requirements
RUN apt-get install -y tmux git python3-pip python3-pandas python3-docopt python3-msgpack python3-jinja2
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /opt/

# downloading gyoithon
RUN git clone https://github.com/gyoisamurai/GyoiThon.git

WORKDIR /opt/GyoiThon

# installing python requirements
RUN pip3 install -r requirements.txt
# copying over config.ini without Japanese Characters
COPY config.ini .

CMD ["python3", "gyoithon.py", "-m", "-e", "-c", "-s"]
```

Error I get:
```
root@74b88209d469:/opt/GyoiThon# python3 gyoithon.py                                                  
Traceback (most recent call last):                                                                    
  File "gyoithon.py", line 235, in <module>                                                           
    show_banner(utility)                                                                              
  File "gyoithon.py", line 83, in show_banner                                                         
    utility.print_message(NONE, banner)                                                               
  File "/opt/GyoiThon/util.py", line 115, in print_message                                            
    print(NOTE_GREEN + message + ENDC)                                                                
UnicodeEncodeError: 'ascii' codec can't encode characters in position 82-91: ordinal not in range(128)
```
I also got unicode errors with the original config.ini file. I removed a bunch of Japanese characters which fixed that error. As far as I can tell util.py has no Japanese characters. 

Is there an easy fix to this? My research says its related to the locales, switching the locale to be in Japan does not fix this issue.

I really appreciate your help

**Comment by fargusplumdoodle** [comment]
UPDATE! IT WORKS!!

I might see if I can make the dockerfile download all the cves. Is this helpful? Should I fork and make a pull request? Im new to this whole opensource thing.
```
# 
# SST API Gyoithon Dockerfile!
#

FROM ubuntu:latest

ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8

# preventing one of the installs from requesting user input
COPY ./timezonefix.sh /tmp/timezonefix.sh

# Procedure
#    1. updating package lists
#    2. fixing timezone issue
#    3. installing dependancies   
#    4/5. cleaning up
#    6. Downloading gyoithon
RUN apt-get update && \
	bash /tmp/timezonefix.sh && \
	apt-get install -y tmux git python3-pip python3-pandas \
		 python3-docopt python3-msgpack python3-jinja2 && \ 
	apt-get clean && \
	rm -rf /var/lib/apt/lists/* && \
	git clone https://github.com/gyoisamurai/GyoiThon.git /opt/GyoiThon

WORKDIR /opt/GyoiThon

# installing python requirements
RUN pip3 install -r requirements.txt

CMD ["python3", "gyoithon.py", "-m", "-e", "-c", "-s"]
```

**Comment by 13o-bbr-bbq** [comment]
Thank you for your challenging!
I think your idea is very cool. Could you make a pull request?

**Comment by fargusplumdoodle** [comment]
Im doing a bit more testing to ensure it all works but I totally will! It should be done by friday.

**Comment by 13o-bbr-bbq** [comment]
Thank you!!
I really appreciate your great help.
