### ISSUE TITLE
Vulns_nvd.csv

### ISSUE THREAD

**Issue by Shravani0706** [gyoisamurai/GyoiThon#47]
I am getting an error saying there is no vulns_nvd.csv file. I am trying to find the vulns_nvd.csv file, could not locate it.  I need help please.

**Comment by xSneaky** [comment]
In your config.ini edit to this
Line 93: nvd_meta_url         : https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-*.meta
&
Line 94: nvd_zip_url          : https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-*.json.zip
should work after

**Comment by honors1** [comment]
> In your config.ini edit to this
> Line 93: nvd_meta_url : https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-*.meta
> &
> Line 94: nvd_zip_url : https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-*.json.zip
> should work after

----------------
I changed URLs to them.
I got the error message as follows:

[*] Load vulnerability database : /home/kali/Downloads/GyoiThon/modules/vuln_db/vulns_nvd.csv
Traceback (most recent call last):
  File "/home/kali/Downloads/GyoiThon/gyoithon.py", line 212, in <module>
    cve_explorer = CveExplorerNVD(utility, opt_no_update_vulndb)
  File "/home/kali/Downloads/GyoiThon/modules/Gyoi_CveExplorerNVD.py", line 78, in __init__
    self.df_vuln_db = self.initialize_vuln_db()
  File "/home/kali/Downloads/GyoiThon/modules/Gyoi_CveExplorerNVD.py", line 304, in initialize_vuln_db
    df_vuln_db = pd.read_csv(self.nvd_path, sep=',', encoding='utf-8')
  File "/home/kali/miniconda3/envs/GyoiThon/lib/python3.9/site-packages/pandas/io/parsers.py", line 688, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/kali/miniconda3/envs/GyoiThon/lib/python3.9/site-packages/pandas/io/parsers.py", line 454, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/home/kali/miniconda3/envs/GyoiThon/lib/python3.9/site-packages/pandas/io/parsers.py", line 948, in __init__
    self._make_engine(self.engine)
  File "/home/kali/miniconda3/envs/GyoiThon/lib/python3.9/site-packages/pandas/io/parsers.py", line 1180, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/kali/miniconda3/envs/GyoiThon/lib/python3.9/site-packages/pandas/io/parsers.py", line 1993, in __init__
------------

Where can I find the 'vulns_nvd.csv'??

**Comment by gyoisamurai** [comment]
We fixed `config.ini`.
Please, check it.
https://github.com/gyoisamurai/GyoiThon/blob/master/config.ini
